kind: Pod
apiVersion: v1
metadata:
  name: sidecard-test
spec:
  containers:
    # Produce Log
  - name: main-container
    image: busybox:latest
    command: ["sh","-c","while true;do echo 'hello dosto'>> /var/log/app.log;sleep 10;  done;"]
    volumeMounts:
    - name: shared-logs
      mountPath: /var/log/
    # Display Log
  - name: sidecar-container
    image: busybox:latest
    command: ["sh","-c","tail -f  /var/log/app.log"]
    volumeMounts:
    - name: shared-logs
      mountPath: /var/log/

  volumes:
  - name: shared-logs
    emptyDir: {}
