kind: ReplicaSet
apiVersion: apps/v1
metadata:
  name: nginx-replicaset
  namespace: nginx-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-pod
  template:
    metadata:
      name: nginx-replicaset-pod
      labels:
        app: nginx-pod
    spec:
      containers:
        - name: nginx-cont
          image: nginx:latest
          ports:
            - containerPort: 80


