kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx-deployment
  namespace: nginx-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-pod
  template:
    metadata:
      name: nginx-dep-pod
      labels:
        app: nginx-pod
    spec:
      containers:
        - name: nginx-cont
          image: nginx:latest
          ports:
            - containerPort: 80


