kind: Service
apiVersion: v1
metadata:
  name: nginx-service
  namespace: nginx-ns
spec: 
  selector:
    app: nginx-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
  
