kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1
metadata:
  name: devopsbatches.trainwithshubham.com
spec:
  group: trainwithshubham.com
  names: 
    plural: devopsbatches
    singular: devopsbatch
    kind: DevopsBatch
    shortNames:
      - junoon
      - bathes
      - tws
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties: 
           spec: 
            type: object
            properties: 
              name: 
                type: string
                description: This is the name of the devops batch

              duration: 
                type: string 
                description: this is the duration of the devops batch
              mode: 
                type: string
                description: this is the mode of the devops batch
              platform: 
                type: string
                description: this is the platform of the devops batch

