kind: VerticalPodAutoscaler
apiVersion: autoscaling.k8s.io/v1
metadata:
  name: apache-vpa
  namespace: apache-ns
spec:
  targetRef:
    name: apache-dep
    apiVersion: apps/v1
    kind: Deployment
  updatePolicy:
    updateMode: "Auto" 


